[style.description]
foreground = { rgb = { r = 192, g = 202, b = 245 } } # c0caf5 (foreground)
underline = false
bold = false
italic = false

[style.command_name]
foreground = { rgb = { r = 125, g = 207, b = 255 } } # 7dcfff (cyan/light blue)
underline = false
bold = true
italic = false

[style.example_text]
foreground = { rgb = { r = 158, g = 206, b = 106 } } # 9ece6a (green)
underline = false
bold = false
italic = false

[style.example_code]
foreground = { rgb = { r = 122, g = 162, b = 247 } } # 7aa2f7 (blue)
underline = false
bold = false
italic = false

[style.example_variable]
foreground = { rgb = { r = 187, g = 154, b = 247 } } # bb9af7 (purple)
underline = true
bold = false
italic = false

[display]
compact = true
use_pager = false

[updates]
auto_update = false
auto_update_interval_hours = 720

[directories]
