---
- name: MacOSX | Install Homebrew formulae
  community.general.homebrew:
    name: "{{ common_packages + macos_packages }}"
    state: present

- name: MacOSX | Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ macos_casks }}"
    state: present
