---
- name: Include macOS specific tasks
  ansible.builtin.include_tasks: macos.yml
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Include Fedora specific tasks
  ansible.builtin.include_tasks: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'
