[tools]
gh = "latest"
lazygit = "latest"
usage = "latest"
node = "latest"
go = "latest"
tlrc = "latest"
uv = "latest"
bat = "latest"
"npm:bash-language-server" = "latest"
podlet = "latest"
podman-tui = "latest"
bitwarden = "latest"
fd = "latest"
rg = "latest"
"pipx:ansible-dev-tools" = { version = "latest", uvx_args = "--with-executables-from ansible-core,ansible-lint,ansible-navigator,ansible-creator,ansible-builder,ansible-runner,ansible-sign,ansible-dev-environment,molecule,tox,pytest,yamllint,bindep" }
"pipx:ruff" = "latest"
"pipx:ty" = "latest"
btop = "latest"
shellcheck = "latest"
shfmt = "latest"
herdr = "latest"
starship = "latest"
lnav = "latest"
rust-analyzer = "latest"
godot = "latest"
watchexec = "latest"
television = "latest"
fastfetch = "latest"
zoxide = "latest"
"npm:@doist/todoist-cli" = "latest"
gopass = "latest"
bitwarden-secrets-manager = "latest"
delta = "latest"
opentofu = "latest"
"go:github.com/bootdotdev/bootdev" = "latest"
rust = "latest"
terraform-ls = "latest"
ffmpeg = "latest"
codex = "latest"
"aqua:nushell/nushell" = "latest"
carapace = "latest"

[settings]
experimental = true

[settings.dotfiles]
root = "~/.config/mise/dotfiles"
default_mode = "symlink"

[dotfiles]
"~/.config/mise/config.toml" = { source = "~/.config/mise/dotfiles/config-mise/config.toml" }
"~/.config/mise/tasks" = { source = "~/.config/mise/dotfiles/mise-tasks" }
"~/.config/helix/config.toml" = { source = "~/.config/mise/dotfiles/config-helix/config.toml" }
"~/.config/helix/languages.toml" = { source = "~/.config/mise/dotfiles/config-helix/languages.toml" }
"~/.config/herdr/config.toml" = { source = "~/.config/mise/dotfiles/config-herdr/config.toml.tmpl", mode = "template" }
"~/.config/nushell/config.nu" = { source = "~/.config/mise/dotfiles/config-nushell/config.nu" }
"~/.config/nushell/autoload/00-env.nu" = { source = "~/.config/mise/dotfiles/config-nushell/autoload/00-env.nu" }
"~/.config/nushell/env.nu" = { source = "~/.config/mise/dotfiles/config-nushell/env.nu" }
"~/.bashrc.d/90-mise.sh" = { source = "~/.config/mise/dotfiles/config-bash/90-mise.sh" }

[bootstrap.hooks.pre-tools]
run = "mise install go"

