---
# Fedora specific packages
fedora_packages:
  - bat
  - cargo
  - eza
  - fd-find
  - fish
  - fzf
  - gcc
  - gh
  - git
  - lazygit
  - make
  - neovim
  - podlet
  - podman
  - podman-tui
  - ripgrep
  - starship
  - tealdeer
  - tmux
  - uv
  # Commented out until fixed on F42
  # - ghostty

# Fedora COPR repositories
fedora_copr_repos:
  # - pgdev/ghostty
  - atim/lazygit
  - atim/starship
  - alternateved/eza

# Fedora flatpaks
fedora_flatpaks:
  - com.github.johnfactotum.Foliate
  - com.github.tchx84.Flatseal
  - io.github.flattool.Warehouse
  - com.valvesoftware.Steam
  - com.spotify.Client
