[tools]
gh      = "latest"
lazygit = "latest"
usage = "latest"
node = "latest"
tlrc = "latest"
claude = "latest"
uv = "latest"
fzf = "latest"
bat = "latest"
yq = "latest"
"npm:@ansible/ansible-language-server" = "latest"
miller = "latest"
ollama = "latest"
"github:SilasMarvin/lsp-ai" = "latest"
"npm:bash-language-server" = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
podlet = "latest"
podman-tui = "latest"
bitwarden = "latest"
fd = "latest"
rg = "latest"
"pipx:ansible-dev-tools" = { version = "latest", uvx_args = "--with-executables-from ansible-core,ansible-lint,ansible-navigator,ansible-creator,ansible-builder,ansible-runner,ansible-sign,ansible-dev-environment,molecule,tox,pytest,yamllint,bindep" }
"pipx:ruff" = "latest"
"pipx:ty" = "latest"
helix = "latest"
chezmoi = "latest"
btop = "latest"
