---
- name: Fedora | Apply Fedora-specific file additions
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - path: "{{ ansible_env.HOME }}/.config/ghostty/config"
      insertafter: '# Options'
      line: |-
        window-theme = ghostty
        command = /usr/bin/fish
        font-size = 14
        gtk-titlebar-hide-when-maximized = true

- name: Fedora | Ensure Foliate theme directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.var/app/com.github.johnfactotum.Foliate/config/com.github.johnfactotum.Foliate/themes"
    state: directory
    mode: '0755'

- name: Fedora | Create Foliate theme symlink
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.config/foliate/tokyonight_night.json"
    dest: "{{ ansible_env.HOME }}/.var/app/com.github.johnfactotum.Foliate/config/com.github.johnfactotum.Foliate/themes/tokyonight_night.json"
    state: link
    force: true
