---
- name: Fedora | Apply Fedora-specific file modifications
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - path: "{{ ansible_env.HOME }}/.config/ghostty/config"
      regexp: 'command = /opt/homebrew/bin/fish'
      replace: 'command = /usr/bin/fish'
    - path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
      regexp: '# homebrew\n    /opt/homebrew/bin/brew shellenv \| source\n'
      replace: ''

- name: Fedora | Ensure Foliate theme directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.var/app/com.github.johnfactotum.Foliate/config/com.github.johnfactotum.Foliate/themes"
    state: directory
    mode: '0755'

- name: Fedora | Create Foliate theme symlink
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.config/foliate/tokyonight_night.json"
    dest: "{{ ansible_env.HOME }}/.var/app/com.github.johnfactotum.Foliate/config/com.github.johnfactotum.Foliate/themes/tokyonight_night.json"
    state: link
    force: true
