---
- name: MacOSX | Apply MacOSX-specific file additions
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
      insertafter: 'if status is-interactive'
      line: '    # homebrew\n    /opt/homebrew/bin/brew shellenv \| source\n'

    - path: "{{ ansible_env.HOME }}/.config/ghostty/config"
      insertafter: '# Options'
      line: |
        command = /opt/homebrew/bin/fish
        font-size = 18
        macos-option-as-alt = true

- name: MacOSX | Ensure tealdeer directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Library/Application Support/tealdeer"
    state: directory
    mode: '0755'

- name: MacOSX | Create tealdeer config symlink
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.config/tealdeer/config.toml"
    dest: "{{ ansible_env.HOME }}/Library/Application Support/tealdeer/config.toml"
    state: link
    force: true
