---
- name: Synchronize config directory to user's ~/.config
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/config/"
    dest: "{{ ansible_env.HOME }}/.config/"
    recursive: true

- name: Include Fedora specific tasks
  ansible.builtin.include_tasks: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- name: Include macOS specific tasks
  ansible.builtin.include_tasks: macos.yml
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Build bat cache
  ansible.builtin.command: bat cache --build
  changed_when: false
